# Generated by Django 2.1.7 on 2019-04-08 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190327_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='grammar_nonTerminal_symbols',
            field=models.TextField(default='a,b,c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammar',
            name='grammar_terminal_symbols',
            field=models.TextField(default='a,b,c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 7, 7, 44, 537360, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
