# Generated by Django 2.1.7 on 2019-04-08 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190408_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 8, 8, 53, 32, 718978, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
