# Generated by Django 2.1.7 on 2019-04-10 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190408_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='grammar_first_set',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grammar',
            name='grammar_follow_set',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 9, 12, 41, 558440, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
