# Generated by Django 2.1.7 on 2019-04-18 13:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190410_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 13, 45, 5, 500632, tzinfo=utc), verbose_name='Date submitted'),
        ),
        migrations.AlterField(
            model_name='grammar',
            name='grammar_user_submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
