# Generated by Django 2.2.1 on 2019-05-31 07:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190418_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 7, 48, 3, 859064, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
