# Generated by Django 2.2.1 on 2019-05-31 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190531_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammar',
            name='grammar_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 31, 8, 41, 22, 477954, tzinfo=utc), verbose_name='Date submitted'),
        ),
    ]
